<?php

namespace App\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
    public function getHomeArticles(){
        $query = $this->createQueryBuilder('a')
                ->select('a')
                ->setMaxResults(3);
        
        return $query->getQuery()->getResult();
    }
    
}
